import { Bell, Download, FileBarChart2, IndianRupee, LockKeyhole, Plus, ShieldAlert, Truck, Users } from "lucide-react";
import { useMemo, useState } from "react";
import { toast } from "sonner";
import { Badge } from "../components/ui/badge";
import { Button } from "../components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "../components/ui/card";
import { Input } from "../components/ui/input";
import { Table, TableCell, TableHead } from "../components/ui/table";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "../components/ui/tabs";
import { CostBars } from "../components/Charts";
import { adminDashboard, calculations, grades, metals, notices, rawMaterials } from "../data/fixtures";
import { shortDate, inr } from "../lib/utils";

export function MastersPage({ focus = "metals" }: { focus?: "metals" | "suppliers" | "users" | "settings" }) {
  const [query, setQuery] = useState("");
  const metalRows = useMemo(() => metals.filter((metal) => `${metal.name} ${metal.code}`.toLowerCase().includes(query.toLowerCase())), [query]);
  return <div className="flex flex-col gap-4"><PageHead title={focus === "suppliers" ? "Supplier Management" : focus === "users" ? "Users & Roles" : focus === "settings" ? "Cost Settings" : "Masters & Price Master"} icon={focus === "suppliers" ? Truck : focus === "users" ? Users : IndianRupee} /><div className="flex flex-wrap gap-2"><Input className="max-w-sm" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search master data..." /><Button onClick={() => toast.success("Creation form is ready for API-backed master data.")}><Plus />Add Record</Button></div>
    {focus === "users" ? <UsersPanel /> : focus === "settings" ? <SettingsPanel /> : focus === "suppliers" ? <SuppliersPanel /> :
    <Tabs defaultValue="metals"><TabsList><TabsTrigger value="metals">Metals</TabsTrigger><TabsTrigger value="grades">Grades</TabsTrigger><TabsTrigger value="raw">Raw Materials</TabsTrigger><TabsTrigger value="prices">Price History</TabsTrigger></TabsList>
      <TabsContent value="metals"><Card><CardContent className="overflow-x-auto p-0"><Table><thead><tr><TableHead>Metal</TableHead><TableHead>Code</TableHead><TableHead>Category</TableHead><TableHead>Grade Count</TableHead><TableHead>Master Price</TableHead><TableHead>Status</TableHead></tr></thead><tbody>{metalRows.map((metal) => <tr key={metal.id}><TableCell className="font-semibold">{metal.name}</TableCell><TableCell>{metal.code}</TableCell><TableCell>{metal.category}</TableCell><TableCell>{metal.grades.length}</TableCell><TableCell>{inr(metal.prices[0]?.pricePerUnit)} / kg</TableCell><TableCell><Badge className="border-[#bde4cf] bg-[#e8fbf0] text-[#087443]">Active</Badge></TableCell></tr>)}</tbody></Table></CardContent></Card></TabsContent>
      <TabsContent value="grades"><GridTable rows={grades.map((grade) => ({ name: grade.name, source: grade.metal?.name, value: `${grade.multiplier}x`, extra: inr(grade.extraPrice) }))} columns={["Grade", "Metal", "Multiplier", "Extra Price"]} /></TabsContent>
      <TabsContent value="raw"><GridTable rows={rawMaterials.map((raw) => ({ name: raw.name, source: raw.code, value: `${inr(raw.prices[0].pricePerUnit)} / kg`, extra: "Master locked" }))} columns={["Raw Material", "Code", "Price", "Policy"]} /></TabsContent>
      <TabsContent value="prices"><GridTable rows={[...metals, ...rawMaterials].map((item) => ({ name: item.name, source: item.prices[0]?.source, value: inr(item.prices[0]?.pricePerUnit), extra: shortDate(item.prices[0]?.effectiveFrom) }))} columns={["Item", "Source", "Current Price", "Effective From"]} /></TabsContent>
    </Tabs>}</div>;
}
function GridTable({ rows, columns }: { rows: Array<{ name?: string; source?: string; value?: string; extra?: string }>; columns: string[] }) {
  return <Card><CardContent className="overflow-x-auto p-0"><Table><thead><tr>{columns.map((column) => <TableHead key={column}>{column}</TableHead>)}</tr></thead><tbody>{rows.map((row, index) => <tr key={`${row.name}-${index}`}><TableCell className="font-semibold">{row.name}</TableCell><TableCell>{row.source}</TableCell><TableCell>{row.value}</TableCell><TableCell>{row.extra}</TableCell></tr>)}</tbody></Table></CardContent></Card>;
}
function SuppliersPanel() {
  return <div className="grid gap-4 xl:grid-cols-[1.2fr_.8fr]"><GridTable columns={["Supplier", "Code", "Linked Price Sheet", "Status"]} rows={[{ name: "JSW Approved Supply Desk", source: "SUP-JSW-01", value: "7 price lines", extra: "Active" }, { name: "Tata Alloy Quotes", source: "SUP-TA-04", value: "CSV ready", extra: "Review" }]} /><Card><CardHeader><CardTitle>Supplier Price Sheets</CardTitle></CardHeader><CardContent className="flex flex-col gap-2 text-sm"><p>Contact details and linked metal prices stay separate from current master prices until Admin activates a price row.</p><Button variant="outline"><Download />CSV Import / Export</Button></CardContent></Card></div>;
}
function UsersPanel() {
  return <div className="grid gap-4 xl:grid-cols-[1.3fr_.7fr]"><GridTable columns={["User", "Email", "Role", "Status"]} rows={[{ name: "Admin User", source: "admin@jsw-mcms.local", value: "Admin", extra: "Active" }, { name: "Rahul Sharma", source: "procurement@jsw-mcms.local", value: "Procurement", extra: "Active" }, { name: "Meera Iyer", source: "finance@jsw-mcms.local", value: "Finance", extra: "Active" }, { name: "Neha Verma", source: "production@jsw-mcms.local", value: "Production", extra: "Active" }]} /><Card><CardHeader><CardTitle>Role Access</CardTitle></CardHeader><CardContent className="flex flex-col gap-2">{["Admin: all modules", "Procurement: costing + supplier visibility", "Finance: review + reports + audit", "Production: costing + comparison"].map((line) => <div key={line} className="rounded-md border p-2 text-sm">{line}</div>)}</CardContent></Card></div>;
}
function SettingsPanel() {
  return <div className="grid gap-4 xl:grid-cols-2"><GridTable columns={["Charge", "Rule", "Value", "Policy"]} rows={[{ name: "GST", source: "Percentage", value: "18%", extra: "Master locked" }, { name: "Scrap", source: "Base cost", value: "2%", extra: "Future calculations" }, { name: "Transport", source: "Per kg", value: "₹ 1.50", extra: "Taxable" }, { name: "Inspection", source: "Flat", value: "₹ 120", extra: "Additional" }]} /><Card><CardHeader><CardTitle>Security Settings</CardTitle></CardHeader><CardContent className="grid gap-2 text-sm sm:grid-cols-2"><Box title="JWT Sessions" value="Access + refresh" /><Box title="Password Policy" value="bcrypt + lockout" /><Box title="Helmet" value="Security headers" /><Box title="Rate Limit" value="Login protected" /></CardContent></Card></div>;
}

export function ReportsPage() {
  return <div className="flex flex-col gap-4"><PageHead title="Reports & Export" icon={FileBarChart2} /><div className="grid gap-3 md:grid-cols-4"><Box title="Cost Reports" value="Daily / Monthly" /><Box title="Trend Reports" value="Price + usage" /><Box title="Comparison Reports" value="Grade decisions" /><Box title="Exports" value="PDF + Excel" /></div><div className="grid gap-4 xl:grid-cols-[1fr_1fr]"><Card><CardHeader><CardTitle>Monthly Cost Trend</CardTitle></CardHeader><CardContent><CostBars points={adminDashboard.series} /></CardContent></Card><Card><CardHeader><CardTitle>Report Actions</CardTitle></CardHeader><CardContent className="flex flex-col gap-2">{["Cost Summary by Alloy", "Monthly Calculation Trend", "Comparison Report"].map((title) => <div key={title} className="flex flex-wrap items-center justify-between gap-2 rounded-md border p-3"><strong className="text-sm">{title}</strong><span className="flex gap-2"><a className="inline-flex h-8 items-center rounded-md border px-3 text-xs font-semibold" href="http://localhost:4000/api/exports/calculations/calc-1023/pdf">PDF</a><Button variant="outline" size="sm" onClick={() => toast.success("Excel export uses the report API with auth.")}>Excel</Button></span></div>)}</CardContent></Card></div><ReportTable /></div>;
}
function ReportTable() {
  return <Card><CardHeader><CardTitle>Calculation Report</CardTitle></CardHeader><CardContent className="overflow-x-auto p-0"><Table><thead><tr><TableHead>Batch</TableHead><TableHead>Name</TableHead><TableHead>Qty</TableHead><TableHead>Base</TableHead><TableHead>GST</TableHead><TableHead>Total</TableHead></tr></thead><tbody>{calculations.map((row) => <tr key={row.id}><TableCell>{row.batchId}</TableCell><TableCell className="font-semibold">{row.name}</TableCell><TableCell>{row.totalQuantity} kg</TableCell><TableCell>{inr(row.baseCost)}</TableCell><TableCell>{inr(row.gstAmount)}</TableCell><TableCell>{inr(row.finalCost)}</TableCell></tr>)}</tbody></Table></CardContent></Card>;
}
export function AuditPage() {
  return <div className="flex flex-col gap-4"><PageHead title="Audit Logs & Live Alerts" icon={ShieldAlert} /><div className="grid gap-3 md:grid-cols-4"><Box title="Price Changes" value="100% logged" /><Box title="Login Activity" value="Lockout after 5" /><Box title="Notifications" value="In-app live" /><Box title="Exports" value="Audited" /></div><div className="grid gap-4 xl:grid-cols-[1.2fr_.8fr]"><GridTable columns={["Entity", "Action", "User", "Time"]} rows={[{ name: "Nickel price", source: "PRICE_UPDATE", value: "Admin", extra: "10:15 AM" }, { name: "BATCH-1023", source: "COMPLETE", value: "Rahul Sharma", extra: "09:20 AM" }, { name: "Cost Report", source: "EXPORT_PDF", value: "Meera Iyer", extra: "Yesterday" }]} /><Card><CardHeader><CardTitle>Notification Center</CardTitle></CardHeader><CardContent className="flex flex-col gap-2">{notices.map((notice) => <div key={notice.id} className="rounded-md border p-3"><div className="flex items-center gap-2"><Bell className="size-4 text-[var(--primary)]" /><strong className="text-sm">{notice.title}</strong></div><p className="mt-1 text-xs text-[var(--muted-foreground)]">{notice.message}</p></div>)}</CardContent></Card></div></div>;
}
function Box({ title, value }: { title: string; value: string }) {
  return <Card><CardContent className="p-4"><p className="text-xs font-semibold uppercase text-[var(--muted-foreground)]">{title}</p><strong className="mt-2 block text-xl">{value}</strong></CardContent></Card>;
}
function PageHead({ title, icon: Icon }: { title: string; icon: typeof LockKeyhole }) {
  return <header className="flex items-center gap-3"><span className="grid size-11 place-items-center rounded-lg bg-[#e8f0fb] text-[var(--primary)]"><Icon /></span><div><p className="text-sm font-semibold text-[var(--primary)]">MCMS Core + Admin</p><h2 className="text-2xl font-bold">{title}</h2></div></header>;
}
